# Generated by Django 5.1.3 on 2024-12-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_book_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
