# Generated by Django 5.1.3 on 2024-12-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_book_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz', models.CharField(max_length=255)),
                ('en', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='vocab/audio/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='apps.unit')),
            ],
        ),
    ]
