# Generated by Django 5.1.3 on 2024-12-08 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_unit_unit_name_unit_name_unit_unit_num_vocab'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('right', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=255)),
                ('section_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='apps.testsection')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.SmallIntegerField(default=0)),
                ('incorrect', models.SmallIntegerField(default=0)),
                ('quantity', models.SmallIntegerField()),
                ('type', models.CharField(choices=[('test', 'Test'), ('vocab_text', 'VocabText'), ('vocab_audio', 'VocabAudio'), ('listening', 'Listening'), ('writing', 'Writing'), ('reading', 'Reading'), ('speaking', 'Speaking')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('units', models.ManyToManyField(related_name='results', to='apps.unit')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('test_sections', models.ManyToManyField(related_name='results', to='apps.testsection')),
            ],
        ),
    ]
