# Generated by Django 5.1.3 on 2024-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_testsection_remove_book_images_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
