# Generated by Django 5.1.3 on 2024-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_book_image_book_images_alter_book_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_num',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
